version: "3.8"

services:
  db:
    image: postgres:12.3
    command: postgres -c 'max_connections=1000'
    container_name: kwtool_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=kwtool_dev
    ports:
      - "5432:5432"
